# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol/denoise.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protocol/denoise.proto\x12 utopia.loquista.noisecancelation\"\x7f\n\x14RequestConfiguration\x12\x0e\n\x06simple\x18\x01 \x01(\x08\x12\x12\n\naggressive\x18\x02 \x01(\x08\x12\x43\n\tfrequency\x18\x03 \x01(\x0e\x32\x30.utopia.loquista.noisecancelation.InputFrequency\"\x89\x01\n\x17NoiseCancelationRequest\x12\x13\n\x0b\x61udio_input\x18\x01 \x01(\x0c\x12\x46\n\x06\x63onfig\x18\x02 \x01(\x0b\x32\x36.utopia.loquista.noisecancelation.RequestConfiguration\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"?\n\x0f\x41udioClassifier\x12\x0e\n\x06speech\x18\x01 \x01(\x02\x12\r\n\x05noise\x18\x02 \x01(\x02\x12\r\n\x05music\x18\x03 \x01(\x02\"\x94\x01\n\x18NoiseCancelationResponse\x12\x14\n\x0c\x61udio_output\x18\x01 \x01(\x0c\x12O\n\x14\x61udio_classification\x18\x02 \x01(\x0b\x32\x31.utopia.loquista.noisecancelation.AudioClassifier\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\"\x07\n\x05\x45mpty*0\n\x0eInputFrequency\x12\x0e\n\nFREQ_16KHz\x10\x00\x12\x0e\n\nFREQ_48KHz\x10\x01\x32\x82\x02\n\x07\x44\x65noise\x12\x8f\x01\n\x10NoiseCancelation\x12\x39.utopia.loquista.noisecancelation.NoiseCancelationRequest\x1a:.utopia.loquista.noisecancelation.NoiseCancelationResponse\"\x00(\x01\x30\x01\x12\x65\n\x0fGetServerStatus\x12\'.utopia.loquista.noisecancelation.Empty\x1a\'.utopia.loquista.noisecancelation.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol.denoise_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_INPUTFREQUENCY']._serialized_start=554
  _globals['_INPUTFREQUENCY']._serialized_end=602
  _globals['_REQUESTCONFIGURATION']._serialized_start=60
  _globals['_REQUESTCONFIGURATION']._serialized_end=187
  _globals['_NOISECANCELATIONREQUEST']._serialized_start=190
  _globals['_NOISECANCELATIONREQUEST']._serialized_end=327
  _globals['_AUDIOCLASSIFIER']._serialized_start=329
  _globals['_AUDIOCLASSIFIER']._serialized_end=392
  _globals['_NOISECANCELATIONRESPONSE']._serialized_start=395
  _globals['_NOISECANCELATIONRESPONSE']._serialized_end=543
  _globals['_EMPTY']._serialized_start=545
  _globals['_EMPTY']._serialized_end=552
  _globals['_DENOISE']._serialized_start=605
  _globals['_DENOISE']._serialized_end=863
# @@protoc_insertion_point(module_scope)
